=== chenrenfei/sagacity-db-diversity/src/main/resources/META-INF/sagacity-diversity.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://www.sagframe.com/schema/diversity"
	xmlns:tns="http://www.sagframe.com/schema/diversity"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.sagframe.com/schema/diversity"
	elementFormDefault="qualified">
	<xsd:element name="diversity">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="reference-db" minOccurs="1"
					maxOccurs="1" type="group_datasource" />
				<xsd:element name="target-db" minOccurs="1"
					maxOccurs="1" type="group_datasource" />
			</xsd:sequence>
			<xsd:attribute name="ignore-comment" type="xsd:boolean"
				default="false" />
			<xsd:attribute name="include-tables" type="xsd:string" />
			<xsd:attribute name="exclude-tables" type="xsd:string" />
			<xsd:attribute name="only-differ" type="xsd:boolean" />
			<xsd:attribute name="report-template" type="xsd:string" />
			<xsd:attribute name="report-file" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="group_datasource" mixed="true">
		<xsd:choice minOccurs="1" maxOccurs="unbounded">
			<xsd:element name="url" maxOccurs="1" minOccurs="1">
				<xsd:complexType mixed="true">
					<xsd:attribute name="value" type="xsd:string" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="driver" maxOccurs="1" minOccurs="1">
				<xsd:complexType mixed="true">
					<xsd:attribute name="value" type="xsd:string" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="username" maxOccurs="1" minOccurs="1">
				<xsd:complexType mixed="true">
					<xsd:attribute name="value" type="xsd:string" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="password" maxOccurs="1" minOccurs="1">
				<xsd:complexType mixed="true">
					<xsd:attribute name="value" type="xsd:string" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="catalog" maxOccurs="1" minOccurs="0">
				<xsd:complexType mixed="true">
					<xsd:attribute name="value" type="xsd:string" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="schema" maxOccurs="1" minOccurs="0">
				<xsd:complexType mixed="true">
					<xsd:attribute name="value" type="xsd:string" />
				</xsd:complexType>
			</xsd:element>
		</xsd:choice>
		<xsd:attribute name="name" type="xsd:string" use="optional"/>
	</xsd:complexType>
</xsd:schema>

=== chenrenfei/sagacity-db-diversity/showcase/db-diversity.xml
<?xml version="1.0" encoding="UTF-8"?>
<diversity xmlns="http://www.sagframe.com/schema/diversity"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.sagframe.com/schema/diversity http://www.sagframe.com/schema/sagacity-diversity.xsd"
	include-tables="(?i)\w+">
	<!-- 测试 -->
	<reference-db name="uat">
		<url><![CDATA[jdbc:mysql://192.168.56.109:3306/sqltoy?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8]]>
		</url>
		<driver value="com.mysql.cj.jdbc.Driver" />
		<username value="sqltoy" />
		<password value="sqltoy" />
		<catalog value="sqltoy" />
		<schema value="sqltoy" />
	</reference-db>

	<target-db name="prod">
		<url><![CDATA[jdbc:mysql://192.168.56.109:3306/sqltoy_sharding1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8]]>
		</url>
		<driver value="com.mysql.cj.jdbc.Driver" />
		<username value="sqltoy_sharding1" />
		<password value="sqltoy_sharding1" />
		<catalog value="sqltoy_sharding1" />
		<schema value="sqltoy_sharding1" />
	</target-db>
	
</diversity>

=== chenrenfei/sagacity-db-diversity/src/test/resources/db-diversity.xml
<?xml version="1.0" encoding="UTF-8"?>
<diversity xmlns="http://www.sagframe.com/schema/diversity"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.sagframe.com/schema/diversity http://www.sagframe.com/schema/sagacity-diversity.xsd"
	include-tables="(?i)\w+">
	<!-- 测试 -->
	<reference-db name="test">
		<url><![CDATA[jdbc:mysql://192.168.56.101:3306/sagacity?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8]]>
		</url>
		<driver value="com.mysql.cj.jdbc.Driver" />
		<username value="dev" />
		<password value="dev" />
		<catalog value="dev" />
		<schema value="dev" />
	</reference-db>

	
	<target-db name="uat">
		<url><![CDATA[jdbc:mysql://192.168.56.102:3306/sagacity?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8]]>
		</url>
		<driver value="com.mysql.cj.jdbc.Driver" />
		<username value="uat" />
		<password value="uat" />
		<catalog value="uat" />
		<schema value="uat" />
	</target-db>
	
</diversity>
